const OK: number = 200;
const CREATED: number = 201;
const NO_CONTENT: number = 204;
const BAD_REQUEST: number = 400;
const UNAUTHORIZED: number = 401;
const FORBIDDEN: number = 403;
const NOT_FOUND: number = 404;
const NOT_ACCEPTABLE: number = 406;
const REQUEST_TIMEOUT: number = 408;
const CONFLICT: number = 409;
const GONE: number = 410;
const PRECONDITION_FAILED: number = 412;
const PAYLOAD_TOO_LARGE: number = 413;
const UNPROCESSABLE_ENTITY: number = 422;
const TOO_MANY_REQUESTS: number = 429;
const INTERNAL_SERVER_ERROR: number = 500;
const NOT_IMPLEMENTED: number = 501;
const SERVICE_UNAVAILABLE: number = 503;
const HTTP_VERSION_NOT_SUPPORTED: number = 505;
const NETWORK_AUTHENTICATION_REQUIRED: number = 511;

export {
  UNAUTHORIZED,
  NETWORK_AUTHENTICATION_REQUIRED,
  HTTP_VERSION_NOT_SUPPORTED,
  NOT_IMPLEMENTED,
  TOO_MANY_REQUESTS,
  PAYLOAD_TOO_LARGE,
  PRECONDITION_FAILED,
  NOT_ACCEPTABLE,
  SERVICE_UNAVAILABLE,
  REQUEST_TIMEOUT,
  GONE,
  UNPROCESSABLE_ENTITY,
  CONFLICT,
  FORBIDDEN,
  NO_CONTENT,
  CREATED,
  OK,
  INTERNAL_SERVER_ERROR,
  NOT_FOUND,
  BAD_REQUEST
};
