export interface SensorSpec {
  id: number,
  model: string,
  name: string,
  varName: string,
  unit: string,
  description: string,
  decimalPlaces: number,
  minValue: number,
  maxValue: number,
  lowWarningStart: number,
  lowWarningEnd: number,
  stableStart: number,
  stableEnd: number,
  highWarningStart: number,
  highWarningEnd: number,
  dangerStart: number,
  dangerEnd: number,
}